### ISSUE TITLE
SigV4 for S3

### ISSUE THREAD

**Issue by bakrale** [alephdata/servicelayer#35]
https://github.com/alephdata/servicelayer/blob/d7cdafae7b0c32d4720e9732d0107190bfc7caa0/servicelayer/archive/s3.py#L24

Wondering why SigV4 is not required, or at least an option or environment variable existing to allow it to be enabled, as SigV4 is the recommended signature algorithm for S3 and can cause problems if missing. I see it is commented out here and am curious why

**Comment by pudo** [comment]
I'm not sure anyone is actively running aleph on AWS, so the support for it is somewhat run-down. Very happy to accept pull requests to improve this.

**Comment by sunu** [comment]
Correct me if I'm wrong, IIRC s3v4 is the default option now.
